name: CI

on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  docs:
    name: EF Migration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Setup EF Core
        run: |
          dotnet tool install --global dotnet-ef

      - name: Generate Migration Script
        run: |
          COMMIT_ID="$(git rev-parse --short HEAD)"
          dotnet ef migrations script --idempotent -o "migration_$COMMIT_ID.sql"

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: migration-script
          path: migration_*.sql
          retention-days: 30
